# Allow self-signed certificates
serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
  file:
      filename: /traefik-certs.yml
      watch: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

accessLog: {}
log:
  level: ERROR

api:
  dashboard: true
  insecure: true

http:
  routers:
    catchall:
      rule: "HostRegexp(`{host:.+}`)"
      service: php
      priority: 1
  services:
    php:
      loadBalancer:
        servers:
          - url: "http://php:8080"